import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navigation/Navbar";
import { ToastContainer } from "react-toastify";
import NavbarMobile from "@/components/Navigation/NavbarMobile";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiase`}
      >
        <div className="mb-[4rem] max-sm:hidden">
          <Navbar />
        </div>
        <div className="sm:hidden">
          <NavbarMobile />
        </div>
        <div className="max-sm:mb-[4rem]">{children}</div>
        <ToastContainer autoClose={2000} />
      </body>
    </html>
  );
}
